"""
Mock 数据 — 后端 API 就绪后删除，改用 api_client.py 调真实接口
"""
from datetime import datetime, timedelta

# ============================================================
# P1 上传响应
# ============================================================
MOCK_UPLOAD_RESPONSE = {
    "success": True,
    "data": {
        "report_id": "rpt_mock_001",
        "variant_count": 4250,
        "status": "completed",
        "original_filename": "example_genome.vcf",
        "created_at": datetime.now().isoformat(),
    },
    "error": None,
}

# ============================================================
# P2 分析结果
# ============================================================
MOCK_VARIANTS = [
    {
        "id": "var_001",
        "chromosome": "7",
        "position": 117149150,
        "reference": "CTT",
        "alternative": "C",
        "rs_id": "rs113993960",
        "gene_name": "CFTR",
        "clinvar_significance": "Pathogenic",
        "clinvar_review_status": "reviewed_by_expert_panel",
        "odds_ratio": 3.52,
        "population_frequency": 0.012,
        "quality_score": 0.98,
        "risk_score": 0.87,
    },
    {
        "id": "var_002",
        "chromosome": "13",
        "position": 32890500,
        "reference": "A",
        "alternative": "G",
        "rs_id": "rs1799950",
        "gene_name": "BRCA2",
        "clinvar_significance": "Pathogenic",
        "clinvar_review_status": "reviewed_by_expert_panel",
        "odds_ratio": 4.10,
        "population_frequency": 0.005,
        "quality_score": 0.99,
        "risk_score": 0.92,
    },
    {
        "id": "var_003",
        "chromosome": "17",
        "position": 43092900,
        "reference": "T",
        "alternative": "C",
        "rs_id": "rs80357906",
        "gene_name": "BRCA1",
        "clinvar_significance": "Uncertain significance",
        "clinvar_review_status": "criteria_provided",
        "odds_ratio": None,
        "population_frequency": 0.001,
        "quality_score": 0.76,
        "risk_score": 0.45,
    },
    {
        "id": "var_004",
        "chromosome": "19",
        "position": 44908800,
        "reference": "C",
        "alternative": "T",
        "rs_id": "rs429358",
        "gene_name": "APOE",
        "clinvar_significance": "Pathogenic",
        "clinvar_review_status": "practice_guideline",
        "odds_ratio": 2.80,
        "population_frequency": 0.15,
        "quality_score": 0.99,
        "risk_score": 0.78,
    },
    {
        "id": "var_005",
        "chromosome": "2",
        "position": 47630300,
        "reference": "G",
        "alternative": "A",
        "rs_id": "rs63749897",
        "gene_name": "MSH2",
        "clinvar_significance": "Pathogenic",
        "clinvar_review_status": "reviewed_by_expert_panel",
        "odds_ratio": 3.20,
        "population_frequency": 0.003,
        "quality_score": 0.97,
        "risk_score": 0.83,
    },
    {
        "id": "var_006",
        "chromosome": "3",
        "position": 37089800,
        "reference": "A",
        "alternative": "G",
        "rs_id": "rs1801133",
        "gene_name": "MTHFR",
        "clinvar_significance": "Benign",
        "clinvar_review_status": "criteria_provided",
        "odds_ratio": 0.95,
        "population_frequency": 0.35,
        "quality_score": 0.95,
        "risk_score": 0.12,
    },
    {
        "id": "var_007",
        "chromosome": "11",
        "position": 534200,
        "reference": "C",
        "alternative": "T",
        "rs_id": "rs113488022",
        "gene_name": "HRAS",
        "clinvar_significance": "Pathogenic",
        "clinvar_review_status": "reviewed_by_expert_panel",
        "odds_ratio": 5.00,
        "population_frequency": 0.0001,
        "quality_score": 0.99,
        "risk_score": 0.95,
    },
    {
        "id": "var_008",
        "chromosome": "5",
        "position": 112174000,
        "reference": "T",
        "alternative": "C",
        "rs_id": "rs75527207",
        "gene_name": "APC",
        "clinvar_significance": "Pathogenic",
        "clinvar_review_status": "practice_guideline",
        "odds_ratio": 4.50,
        "population_frequency": 0.002,
        "quality_score": 0.98,
        "risk_score": 0.90,
    },
    {
        "id": "var_009",
        "chromosome": "1",
        "position": 153230000,
        "reference": "G",
        "alternative": "A",
        "rs_id": "rs121908757",
        "gene_name": "LMNA",
        "clinvar_significance": "Conflicting interpretations",
        "clinvar_review_status": "criteria_provided",
        "odds_ratio": None,
        "population_frequency": 0.0005,
        "quality_score": 0.65,
        "risk_score": 0.50,
    },
    {
        "id": "var_010",
        "chromosome": "X",
        "position": 153760000,
        "reference": "A",
        "alternative": "G",
        "rs_id": "rs137852310",
        "gene_name": "F8",
        "clinvar_significance": "Pathogenic",
        "clinvar_review_status": "reviewed_by_expert_panel",
        "odds_ratio": 6.80,
        "population_frequency": 0.0002,
        "quality_score": 0.99,
        "risk_score": 0.97,
    },
]

MOCK_RISK_SCORES = {
    "cardio": 1.80,
    "diabetes": 0.90,
    "breast_cancer": 2.40,
    "colorectal": 1.20,
    "alzheimer": 1.65,
    "obesity": 1.10,
    "hypertension": 1.50,
}

MOCK_ANALYSIS_RESULT = {
    "success": True,
    "data": {
        "report_id": "rpt_mock_001",
        "variants": MOCK_VARIANTS,
        "risk_scores": MOCK_RISK_SCORES,
        "overall_risk_level": "moderate",
        "confidence_intervals": {
            "cardio": [1.40, 2.20],
            "diabetes": [0.60, 1.20],
            "breast_cancer": [1.80, 3.00],
            "colorectal": [0.80, 1.60],
            "alzheimer": [1.20, 2.10],
            "obesity": [0.70, 1.50],
            "hypertension": [1.10, 1.90],
        },
        "quality_score": 0.94,
    },
    "error": None,
}

# ============================================================
# P3 模拟结果
# ============================================================
MOCK_SIMULATION_RESULT = {
    "success": True,
    "data": {
        "scenario_id": "sim_mock_001",
        "health_trajectory": [
            {"year": 0, "risk": 0.08},
            {"year": 1, "risk": 0.09},
            {"year": 2, "risk": 0.10},
            {"year": 3, "risk": 0.12},
            {"year": 4, "risk": 0.14},
            {"year": 5, "risk": 0.16},
            {"year": 10, "risk": 0.22},
            {"year": 15, "risk": 0.30},
            {"year": 20, "risk": 0.38},
        ],
        "confidence_intervals": {
            "upper": [0.08, 0.10, 0.12, 0.15, 0.18, 0.21, 0.29, 0.38, 0.48],
            "lower": [0.08, 0.07, 0.08, 0.09, 0.10, 0.11, 0.15, 0.22, 0.28],
        },
    },
    "error": None,
}

# ============================================================
# P4 建议列表
# ============================================================
MOCK_RECOMMENDATIONS = [
    {
        "id": "rec_001",
        "title": "定期乳腺筛查",
        "description": "鉴于 BRCA1/2 相关风险，建议每年进行一次乳腺 MRI 或超声筛查，早发现早干预。",
        "recommendation_type": "screening",
        "evidence_level": "A",
        "priority_level": 95,
        "difficulty": "🟡 中等",
        "impact_stars": 5,
        "estimated_time": "每年 1 次，约 1 小时",
        "supporting_studies": ["PMID: 29446145", "ClinVar: BRCA1/BRCA2"],
    },
    {
        "id": "rec_002",
        "title": "有氧运动计划",
        "description": "每周至少 150 分钟中等强度有氧运动（快走、游泳、骑行），可显著降低心血管疾病风险。",
        "recommendation_type": "lifestyle",
        "evidence_level": "A",
        "priority_level": 88,
        "difficulty": "🟢 容易",
        "impact_stars": 5,
        "estimated_time": "每周 150 分钟",
        "supporting_studies": ["PMID: 30146384", "AHA Guidelines 2023"],
    },
    {
        "id": "rec_003",
        "title": "低盐饮食",
        "description": "每日钠摄入控制在 2g 以下（约 5g 食盐），有助于控制血压，降低高血压风险。",
        "recommendation_type": "diet",
        "evidence_level": "A",
        "priority_level": 82,
        "difficulty": "🟢 容易",
        "impact_stars": 4,
        "estimated_time": "日常饮食调整",
        "supporting_studies": ["PMID: 30993463", "WHO Salt Reduction"],
    },
    {
        "id": "rec_004",
        "title": "戒烟计划",
        "description": "吸烟会显著增加心血管疾病和多种癌症风险。即使基因风险中等，戒烟仍是最有效的健康干预之一。",
        "recommendation_type": "lifestyle",
        "evidence_level": "A",
        "priority_level": 90,
        "difficulty": "🔴 困难",
        "impact_stars": 5,
        "estimated_time": "持续进行",
        "supporting_studies": ["PMID: 24993553", "Surgeon General Report"],
    },
    {
        "id": "rec_005",
        "title": "低碳水饮食管理",
        "description": "基于 2 型糖尿病遗传易感性，建议减少精制碳水化合物摄入，增加膳食纤维。",
        "recommendation_type": "diet",
        "evidence_level": "B",
        "priority_level": 75,
        "difficulty": "🟡 中等",
        "impact_stars": 4,
        "estimated_time": "日常饮食调整",
        "supporting_studies": ["PMID: 31525701", "ADA Guidelines"],
    },
    {
        "id": "rec_006",
        "title": "定期血糖筛查",
        "description": "每年检测空腹血糖和 HbA1c，早期发现血糖异常，及时干预。",
        "recommendation_type": "screening",
        "evidence_level": "A",
        "priority_level": 78,
        "difficulty": "🟢 容易",
        "impact_stars": 3,
        "estimated_time": "每年 1 次",
        "supporting_studies": ["ADA Screening Guidelines 2024"],
    },
    {
        "id": "rec_007",
        "title": "认知训练与社交活动",
        "description": "基于 APOE 相关阿尔茨海默风险，建议保持活跃的社交生活和认知训练（阅读、棋类、学习新技能）。",
        "recommendation_type": "lifestyle",
        "evidence_level": "B",
        "priority_level": 70,
        "difficulty": "🟢 容易",
        "impact_stars": 3,
        "estimated_time": "每周 3-5 次",
        "supporting_studies": ["PMID: 32580397", "FINGER Study"],
    },
    {
        "id": "rec_008",
        "title": "结直肠癌筛查",
        "description": "基于 MSH2 和 APC 基因变异风险，建议 40 岁起每 3-5 年进行一次结肠镜检查。",
        "recommendation_type": "screening",
        "evidence_level": "A",
        "priority_level": 85,
        "difficulty": "🟡 中等",
        "impact_stars": 5,
        "estimated_time": "每 3-5 年 1 次",
        "supporting_studies": ["PMID: 30146384", "NCCN Guidelines"],
    },
]
